name: Build and Deploy to EB

on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: npm install, build
        run: |
          npm ci
          npm run build
        env:
          CI: true

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: MyZirconApp
          environment_name: zircon-app-dev
          version_label: ${{github.sha}}
          region: us-east-1
          use_existing_version_if_available: true
          deployment_package: deploy.zip
